export const styles = {
  textFillColor: '#9155FD',
  textFillActiveColor: '#ffeeff',
  secondaryTextFillColor: '#ee8800',
  secondaryFillActiveColor: '#ffeeff',
  circleFillColor: '#ffffff',
  circleFillActiveColor: '#9155FD',
  rectStrokeColor: '#bbbbbb',
  arrowColor: 'rgb(0, 134, 114)',
  lineTextColor: 'rgb(0, 134, 114)',
  lineStrokeColor: '#bbbbbb',
  circleStrokeColor: '#9155FD',
  matrixPanelWidth: 660,
  matrixRectStrokeWidth: 1,
  arrowCut: 0.3,
  treePanelWidth: 700,
  lineStrokeWidth: 1,
  strokeWidth: 2,
  levelOffset: 60,
  treeNodeR: 20,
  countCircleR: 8,
  vertexR: 25,
  vertexDistance: 160,

  nodeSpace: 40,
  fontSize: 12,
  fontOffsetY: 12 / 3,
}

export default styles
